Platformauthenticate/Platformauthenticate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('authenticate.urls')),
]

Platformauthenticate/authenticate/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import  views

app_name = 'authenticate'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'authenticate/login.html'), name='login'),
    path('',views.profile, name='profile'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.log_out, name='logout')
]

Platformauthenticate/authenticate/models.py
from django.db import models

# Create your models here.

Platformauthenticate/authenticate/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
        help_texts = {
            'username': None,
            'email': None,
            'password1':None,
            'password2':None,
        }

Platformauthenticate/authenticate/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse

from authenticate.forms import SignUpForm


@login_required
def profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user':user}
    return render(request, 'authenticate/profile.html', args)


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('authenticate:profile')
    else:
        form = SignUpForm()
    return render(request, 'authenticate/signup.html', {'form': form})


def log_out(request):
    logout(request)
    # return  None
    return HttpResponseRedirect(reverse('authenticate:login'))

Platformauthenticate/authenticate/templates/authenticate/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <style>
        .section {
            width: 60%;
            margin: auto;
            display: none;
        }

        @keyframes ldio-33akxueljzj {
            0% {
                transform: translate(-50%, -50%) rotate(0deg);
            }
            100% {
                transform: translate(-50%, -50%) rotate(360deg);
            }
        }

        .ldio-33akxueljzj div {
            position: absolute;
            width: 70px;
            height: 70px;
            border: 6px solid #e15b64;
            border-top-color: transparent;
            border-radius: 50%;
        }

        .ldio-33akxueljzj div {
            animation: ldio-33akxueljzj 1s linear infinite;
            top: 100px;
            left: 100px
        }

        .loadingio-spinner-rolling-9llcrik86o8 {
            width: 200px;
            height: 200px;
            display: inline-block;
            overflow: hidden;
            background: #ffffff;
        }

        .ldio-33akxueljzj {
            width: 100%;
            height: 100%;
            position: relative;
            transform: translateZ(0) scale(1);
            backface-visibility: hidden;
            transform-origin: 0 0; /* see note above */
        }

        .ldio-33akxueljzj div {
            box-sizing: content-box;
        }

        .loader {
            position: fixed;
            height: 100vh;
            width: 100vw;
            display: flex;
            justify-content: center;
            align-items: center;
        }

    </style>


</head>
<body>
<div class="loader">
    <div class="loadingio-spinner-rolling-9llcrik86o8">
        <div class="ldio-33akxueljzj">
            <div></div>
        </div>
    </div>
</div>

<div class="section">
    <h1>Login</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login" class="btn btn-primary">
        <a href="{% url 'authenticate:signup' %}">Sign Up</a>
    </form>
</div>
</body>
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script>
    $(window).on('load', () => {
        $('.loader').fadeOut('slow');
        setTimeout(() => {
            $('.section').fadeIn();
        }, 500);
    })
</script>
</html>

Platformauthenticate/authenticate/templates/authenticate/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <style>
        .section {
            width: 60%;
            margin: auto;
        }
    </style>
</head>
<body>
<div class="section">
    Username: {{ user.username }}
    <br>
    First Name: {{ user.first_name }} &nbsp;
    Last Name: {{ user.last_name }}
    <br>
    Email: {{ user.email }}
    <br>
    <a href="{% url 'authenticate:logout' %} " class='btn btn-primary'> Log Out</a>
</div>
</body>
</html>

Platformauthenticate/authenticate/templates/authenticate/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SignUp</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" rel="stylesheet"/>

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <style>
        .section {
            width: 60%;
            margin: auto;
        }
    </style>
</head>
<body>
<div class="section">
    <h1>SignUp</h1>

    <form action="" method="post" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Sign Up" class="btn btn-primary">

    </form>
    <a href="{% url "authenticate:login" %}">Login</a>
</div>
</body>
</html>